name: Build Android APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip git zip unzip openjdk-17-jdk
          pip install buildozer
      - name: Debug directory structure
        run: |
          echo "Current directory structure:"
          ls -la
          echo "Checking project_300 directory:"
          ls -la project_300 || echo "project_300 directory not found"
      - name: Build APK
        run: |
          cd project_300 || exit 1
          echo "Running buildozer init..."
          buildozer init
          echo "Running buildozer android debug..."
          buildozer -v android debug 2>&1 | tee build.log
          echo "Build log contents:"
          cat build.log
          if [ ! -f "bin/*.apk" ]; then
            echo "Build failed - no APK generated"
            exit 1
          fi
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: project_300/bin/*.apk 
